# Copyright (c) 2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Expose the right-half level only to the split central.
CONFIG_BT_BAS=y

# Uncomment the following lines to enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
