# Copyright (c) 2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Increase Bluetooth transmission power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable deep sleep support
CONFIG_ZMK_SLEEP=y

# Milliseconds of inactivity before entering deep sleep (30 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Enable battery reporting and sensors
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_SENSOR=y

# NFCピンをGPIOとして使用
CONFIG_NFCT_PINS_AS_GPIOS=y

# LED Indicator
CONFIG_INDICATOR_LED_WIDGET=y
CONFIG_INDICATOR_LED_SHOW_BLE=y
